- hosts: all
  vars_files:
      - mountvars.yml
  tasks:
     - mount: 
          path: "{{ mountpoint }}"
          src: "{{ partition}}"
          fstype: "{{ formattype }}"
          state: mounted
